"""Story documents: the spine that connects writing to media production."""

from .binding import (
    SCENE_ID_PARAM,
    SCENE_ROLE_PARAM,
    STORY_ID_PARAM,
    SceneBinder,
    scene_binding_params,
)
from .continuity import (
    MAX_CANON_FACTS,
    MAX_CHAPTER_SUMMARIES,
    MAX_FACT_CHARS,
    MAX_RESOLVED_THREADS,
    MAX_SUMMARY_CHARS,
    MAX_TIMELINE_FACTS,
    MAX_UNRESOLVED_THREADS,
    CanonFact,
    ChapterSummary,
    ContinuityMemory,
    ResolvedThread,
    TimelineFact,
    UnresolvedThread,
)
from .continuity_builder import (
    ChapterCompletion,
    ContinuityUpdateResult,
    ProposedCanonFact,
    ProposedThread,
    ProposedTimelineFact,
    update_continuity_memory,
)
from .continuity_context import (
    CONTINUITY_PROMPT_HEADING,
    DEFAULT_CONTEXT_CHARACTER_BUDGET,
    ContinuityContext,
    build_continuity_context,
    render_continuity_prompt_block,
)
from .continuity_repository import ContinuityRepository
from .merge import DEFAULT_SCENE_DURATION_SECONDS, SUPPORTED_TASKS, apply_text_result
from .repository import StoryRepository
from .schemas import (
    SCENE_ASSET_ROLES,
    STORY_FORMATS,
    Beat,
    Chapter,
    DialogueLine,
    Scene,
    StoryDocument,
)
from .text_utils import count_words, split_subtitle_lines
from .timeline import (
    DEFAULT_MUSIC_GAIN_DB,
    SUPPORTED_MOTIONS,
    build_timeline,
    missing_scene_assets,
    normalize_motion,
    required_scene_roles,
)
from .visual_fanout import (
    STRATEGY_MEDIA_TYPE,
    SceneVisualFanoutResult,
    SceneVisualJobPlan,
    fan_out_scene_visuals,
)
from .visual_manifest import (
    DEFAULT_ASPECT_RATIO,
    BibleSnapshotRef,
    SceneVisualManifest,
    SceneVisualRequest,
    build_visual_manifest,
)
from .visual_strategy import (
    IMAGE_TO_VIDEO,
    KEN_BURNS,
    STILL,
    STRATEGY_FALLBACK_ORDER,
    TEXT_TO_VIDEO,
    VISUAL_STRATEGIES,
    VisualCapabilities,
    VisualResourceBudget,
    VisualStrategyDecision,
    VisualStrategyUnavailableError,
    normalize_visual_intent,
    select_visual_strategy,
)

__all__ = [
    "Beat",
    "BibleSnapshotRef",
    "CONTINUITY_PROMPT_HEADING",
    "CanonFact",
    "Chapter",
    "ChapterCompletion",
    "ChapterSummary",
    "ContinuityContext",
    "ContinuityMemory",
    "ContinuityRepository",
    "ContinuityUpdateResult",
    "DEFAULT_ASPECT_RATIO",
    "DEFAULT_CONTEXT_CHARACTER_BUDGET",
    "DEFAULT_MUSIC_GAIN_DB",
    "DEFAULT_SCENE_DURATION_SECONDS",
    "DialogueLine",
    "IMAGE_TO_VIDEO",
    "KEN_BURNS",
    "MAX_CANON_FACTS",
    "MAX_CHAPTER_SUMMARIES",
    "MAX_FACT_CHARS",
    "MAX_RESOLVED_THREADS",
    "MAX_SUMMARY_CHARS",
    "MAX_TIMELINE_FACTS",
    "MAX_UNRESOLVED_THREADS",
    "ProposedCanonFact",
    "ProposedThread",
    "ProposedTimelineFact",
    "ResolvedThread",
    "SCENE_ASSET_ROLES",
    "STILL",
    "STRATEGY_FALLBACK_ORDER",
    "STRATEGY_MEDIA_TYPE",
    "SUPPORTED_MOTIONS",
    "SCENE_ID_PARAM",
    "SCENE_ROLE_PARAM",
    "STORY_ID_PARAM",
    "SceneBinder",
    "SceneVisualFanoutResult",
    "SceneVisualJobPlan",
    "SceneVisualManifest",
    "SceneVisualRequest",
    "STORY_FORMATS",
    "SUPPORTED_TASKS",
    "Scene",
    "StoryDocument",
    "StoryRepository",
    "TEXT_TO_VIDEO",
    "TimelineFact",
    "UnresolvedThread",
    "VISUAL_STRATEGIES",
    "VisualCapabilities",
    "VisualResourceBudget",
    "VisualStrategyDecision",
    "VisualStrategyUnavailableError",
    "apply_text_result",
    "build_continuity_context",
    "build_timeline",
    "build_visual_manifest",
    "fan_out_scene_visuals",
    "scene_binding_params",
    "count_words",
    "missing_scene_assets",
    "normalize_motion",
    "normalize_visual_intent",
    "render_continuity_prompt_block",
    "required_scene_roles",
    "select_visual_strategy",
    "split_subtitle_lines",
    "update_continuity_memory",
]
