"""Story documents: the spine that connects writing to media production."""

from .binding import (
    SCENE_ID_PARAM,
    SCENE_ROLE_PARAM,
    STORY_ID_PARAM,
    SceneBinder,
    scene_binding_params,
)
from .continuity import (
    MAX_CANON_FACTS,
    MAX_CHAPTER_SUMMARIES,
    MAX_FACT_CHARS,
    MAX_RESOLVED_THREADS,
    MAX_SUMMARY_CHARS,
    MAX_TIMELINE_FACTS,
    MAX_UNRESOLVED_THREADS,
    CanonFact,
    ChapterSummary,
    ContinuityMemory,
    ResolvedThread,
    TimelineFact,
    UnresolvedThread,
)
from .continuity_builder import (
    ChapterCompletion,
    ContinuityUpdateResult,
    ProposedCanonFact,
    ProposedThread,
    ProposedTimelineFact,
    update_continuity_memory,
)
from .merge import DEFAULT_SCENE_DURATION_SECONDS, SUPPORTED_TASKS, apply_text_result
from .repository import StoryRepository
from .schemas import (
    SCENE_ASSET_ROLES,
    STORY_FORMATS,
    Beat,
    Chapter,
    DialogueLine,
    Scene,
    StoryDocument,
)
from .text_utils import count_words, split_subtitle_lines
from .timeline import (
    DEFAULT_MUSIC_GAIN_DB,
    SUPPORTED_MOTIONS,
    build_timeline,
    missing_scene_assets,
    normalize_motion,
)
from .visual_manifest import (
    DEFAULT_ASPECT_RATIO,
    BibleSnapshotRef,
    SceneVisualManifest,
    SceneVisualRequest,
    build_visual_manifest,
)

__all__ = [
    "Beat",
    "BibleSnapshotRef",
    "CanonFact",
    "Chapter",
    "ChapterCompletion",
    "ChapterSummary",
    "ContinuityMemory",
    "ContinuityUpdateResult",
    "DEFAULT_ASPECT_RATIO",
    "DEFAULT_MUSIC_GAIN_DB",
    "DEFAULT_SCENE_DURATION_SECONDS",
    "DialogueLine",
    "MAX_CANON_FACTS",
    "MAX_CHAPTER_SUMMARIES",
    "MAX_FACT_CHARS",
    "MAX_RESOLVED_THREADS",
    "MAX_SUMMARY_CHARS",
    "MAX_TIMELINE_FACTS",
    "MAX_UNRESOLVED_THREADS",
    "ProposedCanonFact",
    "ProposedThread",
    "ProposedTimelineFact",
    "ResolvedThread",
    "SCENE_ASSET_ROLES",
    "SUPPORTED_MOTIONS",
    "SCENE_ID_PARAM",
    "SCENE_ROLE_PARAM",
    "STORY_ID_PARAM",
    "SceneBinder",
    "SceneVisualManifest",
    "SceneVisualRequest",
    "STORY_FORMATS",
    "SUPPORTED_TASKS",
    "Scene",
    "StoryDocument",
    "StoryRepository",
    "TimelineFact",
    "UnresolvedThread",
    "apply_text_result",
    "build_timeline",
    "build_visual_manifest",
    "scene_binding_params",
    "count_words",
    "missing_scene_assets",
    "normalize_motion",
    "split_subtitle_lines",
    "update_continuity_memory",
]
